server:
  port: 8090
spring:
#  mvc:
#    static-path-pattern: /pl/**    #static resources prefix of pl

  resources:
    static-locations: classpath:/pl/
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB       #alone
      max-request-size: 30MB    #totol



person:
  name: kris
  age: 13
  hobbies: [ basketball,swimmming ]
  cars:
    - speed: 280
      name: byd
    - speed: 290
      name: bwm
  secretaries:
    hyn: 8
    yqh: 10
    zsn: 12
    ssc: 13
    lxn: 13
  animals:
     cat:
       color: white
     dog:
       color: yellow

