server:
  port: 8090
spring:
#  mvc:
#    static-path-pattern: /pl/**    #static resources prefix of pl
  datasource:
      username: root
      password: Weixb4818
      url: jdbc:mysql://localhost:3306/mysql_spring
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        aop-patterns: com.atguigu.admin.*  #监控SpringBean
        filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

        stat-view-servlet: # 配置监控页功能
          enabled: true
          login-username: admin   #监控页的账户密码
          login-password: admin
          resetEnable: false

        web-stat-filter: # 监控web
          enabled: true
          urlPattern: /*
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


        filter:
          stat: # 对上面filters里面的stat的详细配置
            slow-sql-millis: 1000
            logSlowSql: true
            enabled: true
          wall: # 对上面filters里面的wall的详细配置
            enabled: true
            config:
              drop-table-allow: false
  resources:
    static-locations: classpath:/pl/
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB       #alone
      max-request-size: 30MB    #totol

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
person:
  name: kris
  age: 13
  hobbies: [ basketball,swimmming ]
  cars:
    - speed: 280
      name: byd
    - speed: 290
      name: bwm
  secretaries:
    hyn: 8
    yqh: 10
    zsn: 12
    ssc: 13
    lxn: 13
  animals:
     cat:
       color: white
     dog:
       color: yellow

